name: Fly Deploy
on:
  push:
    branches:
    - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: rm -rf .angular ./dist
      - run: npx nx build nx-angular-demo:production --verbose
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c .\deploy\fly.toml --dockerfile .\apps\nx-angular-demo\Dockerfile --remote-only
